# -*- indent-tabs-mode:t; -*-
POFILE = conf/locale/en/LC_MESSAGES/django.po
AR_DIR=conf/locale/ar/LC_MESSAGES

all:
	@echo Please pick an option to do!

ensure_pyenv:
	@which tx > /dev/null || (echo 'pybabel is missing! Perhaps you should activate the python environment.' && exit 1)


pybabel_extract: ensure_pyenv
	@# Reset the po file
	rm -rf `dirname $(POFILE)`
	mkdir -p `dirname $(POFILE)`
	echo > $(POFILE)

	pybabel extract --mapping=conf/locale/python.cfg  \
	        --add-comments="Translators:"  \
	        --keyword="interpolate" .  \
	        --output=conf/locale/en/LC_MESSAGES/django.po

i18n_push:
	make ensure_pyenv
	make pybabel_extract

	tx push -l en -s -r edraak-platform.edraak-certificates


i18n_pull:
	make ensure_pyenv

	rm -rf $(AR_DIR)

	tx pull -l ar -r edraak-platform.edraak-certificates --force --mode=reviewed
	msgfmt --check --output $(AR_DIR)/django.mo $(AR_DIR)/django.po

	git add --force $(AR_DIR)/django.{mo,po}
	git commit -m "Update Edraak translations (autogenerated message)" -- $(AR_DIR)
	git push
